// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package SmartBuilding.DistributedSystemCA;

public interface AccessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistributedSystemCA.AccessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  String getUserID();
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>string roomID = 2;</code>
   * @return The roomID.
   */
  String getRoomID();
  /**
   * <code>string roomID = 2;</code>
   * @return The bytes for roomID.
   */
  com.google.protobuf.ByteString
      getRoomIDBytes();
}
