// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package SmartBuilding.DistributedSystemCA;

public interface AccessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistributedSystemCA.AccessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool permissionsGranted = 1;</code>
   * @return The permissionsGranted.
   */
  boolean getPermissionsGranted();
}
