// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightingControlService.proto

package SmartBuilding.DistributedSystemCA;

public final class LightingControlServiceProto {
  private LightingControlServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_LightControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_LightControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_LightControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_LightControlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034LightingControlService.proto\022\023Distribu" +
      "tedSystemCA\"8\n\023LightControlRequest\022\016\n\006ro" +
      "omID\030\001 \001(\t\022\021\n\tsetStatus\030\002 \001(\010\"7\n\024LightCo" +
      "ntrolResponse\022\016\n\006status\030\001 \001(\010\022\017\n\007message" +
      "\030\002 \001(\t2\214\001\n\026LightingControlService\022r\n\027Mon" +
      "itorAndControlLights\022(.DistributedSystem" +
      "CA.LightControlRequest\032).DistributedSyst" +
      "emCA.LightControlResponse(\0010\001BG\n!SmartBu" +
      "ilding.DistributedSystemCAB\033LightingCont" +
      "rolServiceProtoP\001\242\002\002SBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DistributedSystemCA_LightControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DistributedSystemCA_LightControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_LightControlRequest_descriptor,
        new String[] { "RoomID", "SetStatus", });
    internal_static_DistributedSystemCA_LightControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DistributedSystemCA_LightControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_LightControlResponse_descriptor,
        new String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
