// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightingControlService.proto

package SmartBuilding.DistributedSystemCA;

public interface LightControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistributedSystemCA.LightControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomID = 1;</code>
   * @return The roomID.
   */
  String getRoomID();
  /**
   * <code>string roomID = 1;</code>
   * @return The bytes for roomID.
   */
  com.google.protobuf.ByteString
      getRoomIDBytes();

  /**
   * <code>bool setStatus = 2;</code>
   * @return The setStatus.
   */
  boolean getSetStatus();
}
