// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBuilding.proto

package SmartBuilding.DistributedSystemCA;

public interface LightControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistributedSystemCA.LightControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
