// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBuilding.proto

package SmartBuilding.DistributedSystemCA;

public interface LockStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistributedSystemCA.LockStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomID = 1;</code>
   * @return The roomID.
   */
  String getRoomID();
  /**
   * <code>string roomID = 1;</code>
   * @return The bytes for roomID.
   */
  com.google.protobuf.ByteString
      getRoomIDBytes();
}
