// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package SmartBuilding.DistributedSystemCA;

/**
 * Protobuf type {@code DistributedSystemCA.LockStatusResponse}
 */
public final class LockStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DistributedSystemCA.LockStatusResponse)
    LockStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LockStatusResponse.newBuilder() to construct.
  private LockStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LockStatusResponse() {
    lockID_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new LockStatusResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LockStatusResponse.class, Builder.class);
  }

  public static final int LOCKID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object lockID_ = "";
  /**
   * <code>string lockID = 1;</code>
   * @return The lockID.
   */
  @Override
  public String getLockID() {
    Object ref = lockID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      lockID_ = s;
      return s;
    }
  }
  /**
   * <code>string lockID = 1;</code>
   * @return The bytes for lockID.
   */
  @Override
  public com.google.protobuf.ByteString
      getLockIDBytes() {
    Object ref = lockID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      lockID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISLOCKED_FIELD_NUMBER = 2;
  private boolean isLocked_ = false;
  /**
   * <code>bool isLocked = 2;</code>
   * @return The isLocked.
   */
  @Override
  public boolean getIsLocked() {
    return isLocked_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lockID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lockID_);
    }
    if (isLocked_ != false) {
      output.writeBool(2, isLocked_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lockID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lockID_);
    }
    if (isLocked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isLocked_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LockStatusResponse)) {
      return super.equals(obj);
    }
    LockStatusResponse other = (LockStatusResponse) obj;

    if (!getLockID()
        .equals(other.getLockID())) return false;
    if (getIsLocked()
        != other.getIsLocked()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCKID_FIELD_NUMBER;
    hash = (53 * hash) + getLockID().hashCode();
    hash = (37 * hash) + ISLOCKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLocked());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LockStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LockStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LockStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LockStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LockStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LockStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LockStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DistributedSystemCA.LockStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DistributedSystemCA.LockStatusResponse)
      LockStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LockStatusResponse.class, Builder.class);
    }

    // Construct using SmartBuilding.DistributedSystemCA.LockStatusResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lockID_ = "";
      isLocked_ = false;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
    }

    @Override
    public LockStatusResponse getDefaultInstanceForType() {
      return LockStatusResponse.getDefaultInstance();
    }

    @Override
    public LockStatusResponse build() {
      LockStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public LockStatusResponse buildPartial() {
      LockStatusResponse result = new LockStatusResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(LockStatusResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lockID_ = lockID_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isLocked_ = isLocked_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LockStatusResponse) {
        return mergeFrom((LockStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LockStatusResponse other) {
      if (other == LockStatusResponse.getDefaultInstance()) return this;
      if (!other.getLockID().isEmpty()) {
        lockID_ = other.lockID_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIsLocked() != false) {
        setIsLocked(other.getIsLocked());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              lockID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isLocked_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object lockID_ = "";
    /**
     * <code>string lockID = 1;</code>
     * @return The lockID.
     */
    public String getLockID() {
      Object ref = lockID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lockID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string lockID = 1;</code>
     * @return The bytes for lockID.
     */
    public com.google.protobuf.ByteString
        getLockIDBytes() {
      Object ref = lockID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lockID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lockID = 1;</code>
     * @param value The lockID to set.
     * @return This builder for chaining.
     */
    public Builder setLockID(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      lockID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string lockID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLockID() {
      lockID_ = getDefaultInstance().getLockID();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string lockID = 1;</code>
     * @param value The bytes for lockID to set.
     * @return This builder for chaining.
     */
    public Builder setLockIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lockID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean isLocked_ ;
    /**
     * <code>bool isLocked = 2;</code>
     * @return The isLocked.
     */
    @Override
    public boolean getIsLocked() {
      return isLocked_;
    }
    /**
     * <code>bool isLocked = 2;</code>
     * @param value The isLocked to set.
     * @return This builder for chaining.
     */
    public Builder setIsLocked(boolean value) {

      isLocked_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool isLocked = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLocked() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isLocked_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DistributedSystemCA.LockStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:DistributedSystemCA.LockStatusResponse)
  private static final LockStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LockStatusResponse();
  }

  public static LockStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LockStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<LockStatusResponse>() {
    @Override
    public LockStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LockStatusResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LockStatusResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public LockStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

