// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBuilding.proto

package SmartBuilding.DistributedSystemCA;

public interface LockStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistributedSystemCA.LockStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lockID = 1;</code>
   * @return The lockID.
   */
  String getLockID();
  /**
   * <code>string lockID = 1;</code>
   * @return The bytes for lockID.
   */
  com.google.protobuf.ByteString
      getLockIDBytes();

  /**
   * <code>bool isLocked = 2;</code>
   * @return The isLocked.
   */
  boolean getIsLocked();
}
