// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package SmartBuilding.DistributedSystemCA;

public final class SecurityServiceProto {
  private SecurityServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_AccessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_AccessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_AccessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_AccessResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_LockStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_LockStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025SecurityService.proto\022\023DistributedSyst" +
      "emCA\"/\n\rAccessRequest\022\016\n\006userID\030\001 \001(\t\022\016\n" +
      "\006roomID\030\002 \001(\t\",\n\016AccessResponse\022\032\n\022permi" +
      "ssionsGranted\030\001 \001(\010\"#\n\021LockStatusRequest" +
      "\022\016\n\006roomID\030\001 \001(\t\"6\n\022LockStatusResponse\022\016" +
      "\n\006lockID\030\001 \001(\t\022\020\n\010isLocked\030\002 \001(\0102\320\001\n\017Sec" +
      "urityService\022V\n\013GrantAccess\022\".Distribute" +
      "dSystemCA.AccessRequest\032#.DistributedSys" +
      "temCA.AccessResponse\022e\n\020StreamLockStatus" +
      "\022&.DistributedSystemCA.LockStatusRequest" +
      "\032\'.DistributedSystemCA.LockStatusRespons" +
      "e0\001B@\n!SmartBuilding.DistributedSystemCA" +
      "B\024SecurityServiceProtoP\001\242\002\002SBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DistributedSystemCA_AccessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DistributedSystemCA_AccessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_AccessRequest_descriptor,
        new String[] { "UserID", "RoomID", });
    internal_static_DistributedSystemCA_AccessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DistributedSystemCA_AccessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_AccessResponse_descriptor,
        new String[] { "PermissionsGranted", });
    internal_static_DistributedSystemCA_LockStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DistributedSystemCA_LockStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_LockStatusRequest_descriptor,
        new String[] { "RoomID", });
    internal_static_DistributedSystemCA_LockStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_LockStatusResponse_descriptor,
        new String[] { "LockID", "IsLocked", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
