// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdjustAirConditioningTemperatureService.proto

package SmartBuilding.DistributedSystemCA;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistributedSystemCA.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
