// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package SmartBuilding.DistributedSystemCA.service1;

public final class SecurityServiceProto {
  private SecurityServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccessRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DistributedSystemCA.AccessRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userID = 1;</code>
     * @return The userID.
     */
    java.lang.String getUserID();
    /**
     * <code>string userID = 1;</code>
     * @return The bytes for userID.
     */
    com.google.protobuf.ByteString
        getUserIDBytes();

    /**
     * <code>string roomID = 2;</code>
     * @return The roomID.
     */
    java.lang.String getRoomID();
    /**
     * <code>string roomID = 2;</code>
     * @return The bytes for roomID.
     */
    com.google.protobuf.ByteString
        getRoomIDBytes();
  }
  /**
   * <pre>
   *service1: Security Service
   *function1: GrantAccess - unary
   * </pre>
   *
   * Protobuf type {@code DistributedSystemCA.AccessRequest}
   */
  public static final class AccessRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DistributedSystemCA.AccessRequest)
      AccessRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccessRequest.newBuilder() to construct.
    private AccessRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccessRequest() {
      userID_ = "";
      roomID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccessRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_AccessRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_AccessRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SecurityServiceProto.AccessRequest.class, SecurityServiceProto.AccessRequest.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userID_;
    /**
     * <code>string userID = 1;</code>
     * @return The userID.
     */
    @java.lang.Override
    public java.lang.String getUserID() {
      java.lang.Object ref = userID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userID_ = s;
        return s;
      }
    }
    /**
     * <code>string userID = 1;</code>
     * @return The bytes for userID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      java.lang.Object ref = userID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOMID_FIELD_NUMBER = 2;
    private volatile java.lang.Object roomID_;
    /**
     * <code>string roomID = 2;</code>
     * @return The roomID.
     */
    @java.lang.Override
    public java.lang.String getRoomID() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomID_ = s;
        return s;
      }
    }
    /**
     * <code>string roomID = 2;</code>
     * @return The bytes for roomID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomIDBytes() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomID_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SecurityServiceProto.AccessRequest)) {
        return super.equals(obj);
      }
      SecurityServiceProto.AccessRequest other = (SecurityServiceProto.AccessRequest) obj;

      if (!getUserID()
          .equals(other.getUserID())) return false;
      if (!getRoomID()
          .equals(other.getRoomID())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserID().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomID().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SecurityServiceProto.AccessRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.AccessRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.AccessRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.AccessRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SecurityServiceProto.AccessRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *service1: Security Service
     *function1: GrantAccess - unary
     * </pre>
     *
     * Protobuf type {@code DistributedSystemCA.AccessRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DistributedSystemCA.AccessRequest)
        SecurityServiceProto.AccessRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_AccessRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_AccessRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SecurityServiceProto.AccessRequest.class, SecurityServiceProto.AccessRequest.Builder.class);
      }

      // Construct using SmartBuilding.DistributedSystemCA.service1.SecurityServiceProto.AccessRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userID_ = "";

        roomID_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_AccessRequest_descriptor;
      }

      @java.lang.Override
      public SecurityServiceProto.AccessRequest getDefaultInstanceForType() {
        return SecurityServiceProto.AccessRequest.getDefaultInstance();
      }

      @java.lang.Override
      public SecurityServiceProto.AccessRequest build() {
        SecurityServiceProto.AccessRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SecurityServiceProto.AccessRequest buildPartial() {
        SecurityServiceProto.AccessRequest result = new SecurityServiceProto.AccessRequest(this);
        result.userID_ = userID_;
        result.roomID_ = roomID_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SecurityServiceProto.AccessRequest) {
          return mergeFrom((SecurityServiceProto.AccessRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SecurityServiceProto.AccessRequest other) {
        if (other == SecurityServiceProto.AccessRequest.getDefaultInstance()) return this;
        if (!other.getUserID().isEmpty()) {
          userID_ = other.userID_;
          onChanged();
        }
        if (!other.getRoomID().isEmpty()) {
          roomID_ = other.roomID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userID_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                roomID_ = input.readStringRequireUtf8();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object userID_ = "";
      /**
       * <code>string userID = 1;</code>
       * @return The userID.
       */
      public java.lang.String getUserID() {
        java.lang.Object ref = userID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userID = 1;</code>
       * @return The bytes for userID.
       */
      public com.google.protobuf.ByteString
          getUserIDBytes() {
        java.lang.Object ref = userID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userID = 1;</code>
       * @param value The userID to set.
       * @return This builder for chaining.
       */
      public Builder setUserID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserID() {
        
        userID_ = getDefaultInstance().getUserID();
        onChanged();
        return this;
      }
      /**
       * <code>string userID = 1;</code>
       * @param value The bytes for userID to set.
       * @return This builder for chaining.
       */
      public Builder setUserIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object roomID_ = "";
      /**
       * <code>string roomID = 2;</code>
       * @return The roomID.
       */
      public java.lang.String getRoomID() {
        java.lang.Object ref = roomID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string roomID = 2;</code>
       * @return The bytes for roomID.
       */
      public com.google.protobuf.ByteString
          getRoomIDBytes() {
        java.lang.Object ref = roomID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roomID = 2;</code>
       * @param value The roomID to set.
       * @return This builder for chaining.
       */
      public Builder setRoomID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomID() {
        
        roomID_ = getDefaultInstance().getRoomID();
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 2;</code>
       * @param value The bytes for roomID to set.
       * @return This builder for chaining.
       */
      public Builder setRoomIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomID_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DistributedSystemCA.AccessRequest)
    }

    // @@protoc_insertion_point(class_scope:DistributedSystemCA.AccessRequest)
    private static final SecurityServiceProto.AccessRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SecurityServiceProto.AccessRequest();
    }

    public static SecurityServiceProto.AccessRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccessRequest>
        PARSER = new com.google.protobuf.AbstractParser<AccessRequest>() {
      @java.lang.Override
      public AccessRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AccessRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccessRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SecurityServiceProto.AccessRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccessResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DistributedSystemCA.AccessResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool permissionsGranted = 1;</code>
     * @return The permissionsGranted.
     */
    boolean getPermissionsGranted();
  }
  /**
   * Protobuf type {@code DistributedSystemCA.AccessResponse}
   */
  public static final class AccessResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DistributedSystemCA.AccessResponse)
      AccessResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccessResponse.newBuilder() to construct.
    private AccessResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccessResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccessResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_AccessResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_AccessResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SecurityServiceProto.AccessResponse.class, SecurityServiceProto.AccessResponse.Builder.class);
    }

    public static final int PERMISSIONSGRANTED_FIELD_NUMBER = 1;
    private boolean permissionsGranted_;
    /**
     * <code>bool permissionsGranted = 1;</code>
     * @return The permissionsGranted.
     */
    @java.lang.Override
    public boolean getPermissionsGranted() {
      return permissionsGranted_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (permissionsGranted_ != false) {
        output.writeBool(1, permissionsGranted_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (permissionsGranted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, permissionsGranted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SecurityServiceProto.AccessResponse)) {
        return super.equals(obj);
      }
      SecurityServiceProto.AccessResponse other = (SecurityServiceProto.AccessResponse) obj;

      if (getPermissionsGranted()
          != other.getPermissionsGranted()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERMISSIONSGRANTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPermissionsGranted());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SecurityServiceProto.AccessResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.AccessResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.AccessResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.AccessResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SecurityServiceProto.AccessResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DistributedSystemCA.AccessResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DistributedSystemCA.AccessResponse)
        SecurityServiceProto.AccessResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_AccessResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_AccessResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SecurityServiceProto.AccessResponse.class, SecurityServiceProto.AccessResponse.Builder.class);
      }

      // Construct using SmartBuilding.DistributedSystemCA.service1.SecurityServiceProto.AccessResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        permissionsGranted_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_AccessResponse_descriptor;
      }

      @java.lang.Override
      public SecurityServiceProto.AccessResponse getDefaultInstanceForType() {
        return SecurityServiceProto.AccessResponse.getDefaultInstance();
      }

      @java.lang.Override
      public SecurityServiceProto.AccessResponse build() {
        SecurityServiceProto.AccessResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SecurityServiceProto.AccessResponse buildPartial() {
        SecurityServiceProto.AccessResponse result = new SecurityServiceProto.AccessResponse(this);
        result.permissionsGranted_ = permissionsGranted_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SecurityServiceProto.AccessResponse) {
          return mergeFrom((SecurityServiceProto.AccessResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SecurityServiceProto.AccessResponse other) {
        if (other == SecurityServiceProto.AccessResponse.getDefaultInstance()) return this;
        if (other.getPermissionsGranted() != false) {
          setPermissionsGranted(other.getPermissionsGranted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                permissionsGranted_ = input.readBool();

                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private boolean permissionsGranted_ ;
      /**
       * <code>bool permissionsGranted = 1;</code>
       * @return The permissionsGranted.
       */
      @java.lang.Override
      public boolean getPermissionsGranted() {
        return permissionsGranted_;
      }
      /**
       * <code>bool permissionsGranted = 1;</code>
       * @param value The permissionsGranted to set.
       * @return This builder for chaining.
       */
      public Builder setPermissionsGranted(boolean value) {
        
        permissionsGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool permissionsGranted = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPermissionsGranted() {
        
        permissionsGranted_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DistributedSystemCA.AccessResponse)
    }

    // @@protoc_insertion_point(class_scope:DistributedSystemCA.AccessResponse)
    private static final SecurityServiceProto.AccessResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SecurityServiceProto.AccessResponse();
    }

    public static SecurityServiceProto.AccessResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccessResponse>
        PARSER = new com.google.protobuf.AbstractParser<AccessResponse>() {
      @java.lang.Override
      public AccessResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AccessResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccessResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SecurityServiceProto.AccessResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LockStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DistributedSystemCA.LockStatusRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string roomID = 1;</code>
     * @return The roomID.
     */
    java.lang.String getRoomID();
    /**
     * <code>string roomID = 1;</code>
     * @return The bytes for roomID.
     */
    com.google.protobuf.ByteString
        getRoomIDBytes();
  }
  /**
   * <pre>
   *function2: Check lock status - server streaming
   * </pre>
   *
   * Protobuf type {@code DistributedSystemCA.LockStatusRequest}
   */
  public static final class LockStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DistributedSystemCA.LockStatusRequest)
      LockStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LockStatusRequest.newBuilder() to construct.
    private LockStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LockStatusRequest() {
      roomID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LockStatusRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SecurityServiceProto.LockStatusRequest.class, SecurityServiceProto.LockStatusRequest.Builder.class);
    }

    public static final int ROOMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object roomID_;
    /**
     * <code>string roomID = 1;</code>
     * @return The roomID.
     */
    @java.lang.Override
    public java.lang.String getRoomID() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomID_ = s;
        return s;
      }
    }
    /**
     * <code>string roomID = 1;</code>
     * @return The bytes for roomID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomIDBytes() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomID_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SecurityServiceProto.LockStatusRequest)) {
        return super.equals(obj);
      }
      SecurityServiceProto.LockStatusRequest other = (SecurityServiceProto.LockStatusRequest) obj;

      if (!getRoomID()
          .equals(other.getRoomID())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomID().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SecurityServiceProto.LockStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.LockStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.LockStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SecurityServiceProto.LockStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *function2: Check lock status - server streaming
     * </pre>
     *
     * Protobuf type {@code DistributedSystemCA.LockStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DistributedSystemCA.LockStatusRequest)
        SecurityServiceProto.LockStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SecurityServiceProto.LockStatusRequest.class, SecurityServiceProto.LockStatusRequest.Builder.class);
      }

      // Construct using SmartBuilding.DistributedSystemCA.service1.SecurityServiceProto.LockStatusRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomID_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusRequest_descriptor;
      }

      @java.lang.Override
      public SecurityServiceProto.LockStatusRequest getDefaultInstanceForType() {
        return SecurityServiceProto.LockStatusRequest.getDefaultInstance();
      }

      @java.lang.Override
      public SecurityServiceProto.LockStatusRequest build() {
        SecurityServiceProto.LockStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SecurityServiceProto.LockStatusRequest buildPartial() {
        SecurityServiceProto.LockStatusRequest result = new SecurityServiceProto.LockStatusRequest(this);
        result.roomID_ = roomID_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SecurityServiceProto.LockStatusRequest) {
          return mergeFrom((SecurityServiceProto.LockStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SecurityServiceProto.LockStatusRequest other) {
        if (other == SecurityServiceProto.LockStatusRequest.getDefaultInstance()) return this;
        if (!other.getRoomID().isEmpty()) {
          roomID_ = other.roomID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                roomID_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object roomID_ = "";
      /**
       * <code>string roomID = 1;</code>
       * @return The roomID.
       */
      public java.lang.String getRoomID() {
        java.lang.Object ref = roomID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string roomID = 1;</code>
       * @return The bytes for roomID.
       */
      public com.google.protobuf.ByteString
          getRoomIDBytes() {
        java.lang.Object ref = roomID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roomID = 1;</code>
       * @param value The roomID to set.
       * @return This builder for chaining.
       */
      public Builder setRoomID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomID() {
        
        roomID_ = getDefaultInstance().getRoomID();
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 1;</code>
       * @param value The bytes for roomID to set.
       * @return This builder for chaining.
       */
      public Builder setRoomIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomID_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DistributedSystemCA.LockStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:DistributedSystemCA.LockStatusRequest)
    private static final SecurityServiceProto.LockStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SecurityServiceProto.LockStatusRequest();
    }

    public static SecurityServiceProto.LockStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LockStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<LockStatusRequest>() {
      @java.lang.Override
      public LockStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LockStatusRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LockStatusRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SecurityServiceProto.LockStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LockStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DistributedSystemCA.LockStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string lockID = 1;</code>
     * @return The lockID.
     */
    java.lang.String getLockID();
    /**
     * <code>string lockID = 1;</code>
     * @return The bytes for lockID.
     */
    com.google.protobuf.ByteString
        getLockIDBytes();

    /**
     * <code>bool isLocked = 2;</code>
     * @return The isLocked.
     */
    boolean getIsLocked();
  }
  /**
   * Protobuf type {@code DistributedSystemCA.LockStatusResponse}
   */
  public static final class LockStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DistributedSystemCA.LockStatusResponse)
      LockStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LockStatusResponse.newBuilder() to construct.
    private LockStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LockStatusResponse() {
      lockID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LockStatusResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SecurityServiceProto.LockStatusResponse.class, SecurityServiceProto.LockStatusResponse.Builder.class);
    }

    public static final int LOCKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object lockID_;
    /**
     * <code>string lockID = 1;</code>
     * @return The lockID.
     */
    @java.lang.Override
    public java.lang.String getLockID() {
      java.lang.Object ref = lockID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lockID_ = s;
        return s;
      }
    }
    /**
     * <code>string lockID = 1;</code>
     * @return The bytes for lockID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLockIDBytes() {
      java.lang.Object ref = lockID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lockID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISLOCKED_FIELD_NUMBER = 2;
    private boolean isLocked_;
    /**
     * <code>bool isLocked = 2;</code>
     * @return The isLocked.
     */
    @java.lang.Override
    public boolean getIsLocked() {
      return isLocked_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lockID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lockID_);
      }
      if (isLocked_ != false) {
        output.writeBool(2, isLocked_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lockID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lockID_);
      }
      if (isLocked_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isLocked_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SecurityServiceProto.LockStatusResponse)) {
        return super.equals(obj);
      }
      SecurityServiceProto.LockStatusResponse other = (SecurityServiceProto.LockStatusResponse) obj;

      if (!getLockID()
          .equals(other.getLockID())) return false;
      if (getIsLocked()
          != other.getIsLocked()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCKID_FIELD_NUMBER;
      hash = (53 * hash) + getLockID().hashCode();
      hash = (37 * hash) + ISLOCKED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLocked());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SecurityServiceProto.LockStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.LockStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityServiceProto.LockStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SecurityServiceProto.LockStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DistributedSystemCA.LockStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DistributedSystemCA.LockStatusResponse)
        SecurityServiceProto.LockStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SecurityServiceProto.LockStatusResponse.class, SecurityServiceProto.LockStatusResponse.Builder.class);
      }

      // Construct using SmartBuilding.DistributedSystemCA.service1.SecurityServiceProto.LockStatusResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lockID_ = "";

        isLocked_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SecurityServiceProto.internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
      }

      @java.lang.Override
      public SecurityServiceProto.LockStatusResponse getDefaultInstanceForType() {
        return SecurityServiceProto.LockStatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public SecurityServiceProto.LockStatusResponse build() {
        SecurityServiceProto.LockStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SecurityServiceProto.LockStatusResponse buildPartial() {
        SecurityServiceProto.LockStatusResponse result = new SecurityServiceProto.LockStatusResponse(this);
        result.lockID_ = lockID_;
        result.isLocked_ = isLocked_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SecurityServiceProto.LockStatusResponse) {
          return mergeFrom((SecurityServiceProto.LockStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SecurityServiceProto.LockStatusResponse other) {
        if (other == SecurityServiceProto.LockStatusResponse.getDefaultInstance()) return this;
        if (!other.getLockID().isEmpty()) {
          lockID_ = other.lockID_;
          onChanged();
        }
        if (other.getIsLocked() != false) {
          setIsLocked(other.getIsLocked());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                lockID_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                isLocked_ = input.readBool();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object lockID_ = "";
      /**
       * <code>string lockID = 1;</code>
       * @return The lockID.
       */
      public java.lang.String getLockID() {
        java.lang.Object ref = lockID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lockID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lockID = 1;</code>
       * @return The bytes for lockID.
       */
      public com.google.protobuf.ByteString
          getLockIDBytes() {
        java.lang.Object ref = lockID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lockID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lockID = 1;</code>
       * @param value The lockID to set.
       * @return This builder for chaining.
       */
      public Builder setLockID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lockID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lockID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLockID() {
        
        lockID_ = getDefaultInstance().getLockID();
        onChanged();
        return this;
      }
      /**
       * <code>string lockID = 1;</code>
       * @param value The bytes for lockID to set.
       * @return This builder for chaining.
       */
      public Builder setLockIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lockID_ = value;
        onChanged();
        return this;
      }

      private boolean isLocked_ ;
      /**
       * <code>bool isLocked = 2;</code>
       * @return The isLocked.
       */
      @java.lang.Override
      public boolean getIsLocked() {
        return isLocked_;
      }
      /**
       * <code>bool isLocked = 2;</code>
       * @param value The isLocked to set.
       * @return This builder for chaining.
       */
      public Builder setIsLocked(boolean value) {
        
        isLocked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isLocked = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLocked() {
        
        isLocked_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DistributedSystemCA.LockStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:DistributedSystemCA.LockStatusResponse)
    private static final SecurityServiceProto.LockStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SecurityServiceProto.LockStatusResponse();
    }

    public static SecurityServiceProto.LockStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LockStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<LockStatusResponse>() {
      @java.lang.Override
      public LockStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LockStatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LockStatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SecurityServiceProto.LockStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_AccessRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_AccessRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_AccessResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_AccessResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_LockStatusRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_LockStatusRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistributedSystemCA_LockStatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SecurityService.proto\022\023DistributedSyst" +
      "emCA\"/\n\rAccessRequest\022\016\n\006userID\030\001 \001(\t\022\016\n" +
      "\006roomID\030\002 \001(\t\",\n\016AccessResponse\022\032\n\022permi" +
      "ssionsGranted\030\001 \001(\010\"#\n\021LockStatusRequest" +
      "\022\016\n\006roomID\030\001 \001(\t\"6\n\022LockStatusResponse\022\016" +
      "\n\006lockID\030\001 \001(\t\022\020\n\010isLocked\030\002 \001(\0102\320\001\n\017Sec" +
      "urityService\022V\n\013GrantAccess\022\".Distribute" +
      "dSystemCA.AccessRequest\032#.DistributedSys" +
      "temCA.AccessResponse\022e\n\020StreamLockStatus" +
      "\022&.DistributedSystemCA.LockStatusRequest" +
      "\032\'.DistributedSystemCA.LockStatusRespons" +
      "e0\001B@\n!SmartBuilding.DistributedSystemCA" +
      "B\024SecurityServiceProtoP\000\242\002\002SBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DistributedSystemCA_AccessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DistributedSystemCA_AccessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_AccessRequest_descriptor,
        new java.lang.String[] { "UserID", "RoomID", });
    internal_static_DistributedSystemCA_AccessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DistributedSystemCA_AccessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_AccessResponse_descriptor,
        new java.lang.String[] { "PermissionsGranted", });
    internal_static_DistributedSystemCA_LockStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DistributedSystemCA_LockStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_LockStatusRequest_descriptor,
        new java.lang.String[] { "RoomID", });
    internal_static_DistributedSystemCA_LockStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DistributedSystemCA_LockStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistributedSystemCA_LockStatusResponse_descriptor,
        new java.lang.String[] { "LockID", "IsLocked", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
